// src/componentes/header/header.jsx
import React, { useState } from 'react'
import  '../header/header.css';

const Header = () => {
  const [hamburguerOpen,setHamburguerOpen]= useState(false);
  const toggleHamburguer= ( ) =>{
    setHamburguerOpen(!hamburguerOpen)
  }

  return (

    <div className='container-header'>
       <div className='conjunto'>
         <h1 className='logo'>NexaSoft</h1>
        <nav className={`nav-header ${hamburguerOpen ? 'active' : ''}`}>
          <li>Serviços</li>
          <li>Clientes</li>
          <li>Blog</li>
          <li>Contato</li>   
        </nav> 
<div 
      className={`menu-hamburguer ${hamburguerOpen ? 'active' : ''}`} 
      onClick={toggleHamburguer}
    >  
<span className='burger '></span>
<span className='burger '></span>
<span className='burger '></span>

    </div>
    </div>

       </div>
     
  )
}

export default Header;

// src/app/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {

}

<div class="header-container">
  <div class="logo">
    <h1>NexaSoft</h1>
  </div>
  <div class="nav-links">
    <a routerLink="/Home" routerLinkActive="active-link">Home</a>
    <a routerLink="/Empresa" routerLinkActive="active-link">Empresa</a>
    <a routerLink="/Servicos" routerLinkActive="active-link">Serviços</a>
    <a routerLink="/Clientes" routerLinkActive="active-link">Clientes</a>
    <a routerLink="/Blog" routerLinkActive="active-link">Blog</a>
    <a routerLink="/Contato" routerLinkActive="active-link">Contato</a>
  </div>
</div>
